dev_dir: ${oc.env:DEV_PATH}
entity_name: results/release/checkpoints/epoch_400

hydra:
  run:
    dir: ${dev_dir}/im2flow2act/experiment/flow_generation/animateFlow/${entity_name}
  

project_name: AnimateFlow
debug: false

training:
  num_train_epochs: 5000
  log_frequency: 10
  max_train_steps: null
  gradient_accumulation_steps: 1
  gradient_checkpointing: False
  lr_scheduler: "constant"
  lr_warmup_steps: 0
  mixed_precision: "fp16"
  enable_xformers_memory_efficient_attention: True
  # dataloader 
  batch_size: 1 # A100:12
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: True
  drop_last: False
  # ckpt
  ckpt_frequency: 200
  # load_pretrain_weight
  load_pretrain_weight: True

animateflow_kwargs:
  clip_model: "openai/clip-vit-large-patch14"
  global_image_size: [224,224]
  freeze_visual_encoder: True
  global_condition_type: "cls_token"
  emb_dim: 768

load_pretrain_motion_module: False  
lora:
  rank: 128


vae_pretrained_model_path: ${oc.env:DEV_PATH}/checkpoints/decoder/checkpoints/epoch_400
pretrained_model_path: ${oc.env:DEV_PATH}/im2flow2act/pretrain_weights/StableDiffusion1.5
unet_pretrained_model_path: null
use_vae: False
use_clip: True

cfg_random_null_text: True
cfg_random_null_text_ratio: 0.1
max_grad_norm: 1.0

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false


unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  # in_channels: 16

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 48
    temporal_attention_dim_div         : 1
    zero_initialize                    : true


optimizer:
  learning_rate: 1e-4
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-2
  adam_epsilon: 1e-08

dataset_proc_cache_name: <YOUR PREPROCESS OUTPUT DATASET NAME>

dataset:
  _target_: im2flow2act.flow_generation.dataloader.animateflow_dataset.AnimateFlowDataset_Libero
  data_pathes: ["None"]
  grid_size: 16
  frame_sampling_method: "uniform"
  frame_resize_shape: [224,224]
  point_tracking_img_size: [256,256]
  diff_flow: False
  n_sample_frames: 8
  max_episode: 30000
  preprocess: False
  proc_cache: "<YOUR PREPROCESS OUTPUT PATH>/${dataset_proc_cache_name}"
  # max_episode: [4,4,4,4,4]
  dataset_name: bridge

evaluation:
  eval_frequency: 200
  num_samples: 30
  num_inference_steps: 25
  guidance_scale: 8.
  evaluation_save_path: null
  viz_n_points: 256
  draw_line: True
  epoch_dir: ${dev_dir}/im2flow2act/experiment/flow_generation/animateFlow/${entity_name}

  datasets: 
    - _target_: im2flow2act.flow_generation.dataloader.animateflow_dataset.AnimateFlowDataset_Libero
      data_pathes: ["None"]
      grid_size: 16
      n_sample_frames: ${dataset.n_sample_frames}
      frame_sampling_method: "uniform"
      frame_resize_shape: [224,224]
      point_tracking_img_size: [256,256]
      diff_flow: False
      preprocess: False
      proc_cache: "<YOUR PREPROCESS OUTPUT PATH>/${dataset_proc_cache_name}"
      max_episode: 1
      start_episode: 0 
      dataset_name: bridge
